### ISSUE TITLE
Consider replacing kitsu.js with kitsu

### ISSUE THREAD

**Issue by wopian** [KurozeroPB/Jeanne#3]
[kitsu.js](https://yarnpkg.com/en/package/kitsu.js) is deprecated in favour of the more feature complete [kitsu](https://yarnpkg.com/en/package/kitsu) package that is fully JSON-API compliant.

**Comment by KurozeroPB** [comment]
Yes already changed that, I'm using my own [kitsu package](https://www.npmjs.com/package/kawaii-kitsune) which is a fork of kitsu.is + new features. This github is a bit behind on what is actually used to don't sorry about that.
