### ISSUE TITLE
Capitalization doesn't work for the j: command

### ISSUE THREAD

**Issue by TheCNixon** [KurozeroPB/Jeanne#4]
Easy fix

**Comment by TheCNixon** [comment]
![image](https://user-images.githubusercontent.com/10780361/34372685-a78db1e8-ea93-11e7-9828-f62c25095d14.png)
Had something handling this on my bot, seen above with an example command below.

**Comment by KurozeroPB** [comment]
Commands shouldn't be caps insensitive if that's what you're meaning you want.

**Comment by TheCNixon** [comment]
I'm wanting J: to work the same way as j:
Which is a wonderful way to have it work

**Comment by KurozeroPB** [comment]
But why, that seems rather useless. What does it add to bot that there isn't right now? Its basically having 2 prefixes for all commands which could also just be more confusing for some people.

**Comment by TheCNixon** [comment]
It's really not confusing for anyone tho because you're just allowing them the option for capitalization

**Comment by TheCNixon** [comment]
Because right now if you accidentally do it, it doesn't work.

**Comment by KurozeroPB** [comment]
Right it shouldn't work because its a whole other prefix, I'll close this issue since its not gonna happen and it not what anyone should do.
